import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const outfitSans = Outfit({
  variable: "--font-outfit-sans",
  weight: ["300", "500"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Entertainment Web App",
  description: "Generated by FrontEnd Mentor",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfitSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
